name: "Tempest Weather Scraper"
description: "Scrapes weather data from Tempest webpage"
version: "1.0.0"
slug: "tempest_weather_scraper"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  weather_station_id: null
  logging_level: INFO
schema:
  weather_station_id: str
  logging_level: list(DEBUG|INFO|WARN|ERROR|CRITICAL)
homeassistant_api: true
