name: "Tempest Weather Scraper"
description: "Scrapes weather data from Tempest webpage"
version: "1.1.18"
slug: "tempest_weather_scraper"
url: "https://github.com/topher1086/ha-tempest-weather"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  WEATHER_STATION_ID: null
  MQTT_HOST: "core-mosquitto"
  MQTT_PORT: 1884
  MQTT_TRANSPORT: websockets
  MQTT_USER: null
  MQTT_PASS: null
  LOGGING_LEVEL: INFO
schema:
  WEATHER_STATION_ID: str
  MQTT_HOST: str
  MQTT_PORT: int
  MQTT_TRANSPORT: str
  MQTT_USER: str
  MQTT_PASS: password
  LOGGING_LEVEL: list(DEBUG|INFO|WARN|ERROR|CRITICAL)
homeassistant_api: false
