name: "Spotify Repeat Skipper"
description: "Spotify Skipper Addon"
version: "2.0.7"
slug: "spotify_track_skipper"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  spotify_media_players: null
  skip_enabled_helpers: null
  block_for_x_hours: 30
  logging_level: INFO
schema:
  spotify_media_players: str
  skip_enabled_helpers: str
  block_for_x_hours: int(1,300)
  logging_level: list(DEBUG|INFO|WARN|ERROR|CRITICAL)
homeassistant_api: true
